// AUTO-GENERATED by @revenexx/app-sdk-cli — do not edit by hand.
import type { Query } from '@revenexx/app-sdk';

export interface Greetings {
  id?: string;
  name: string;
  message: string;
  locale: string;
  metadata?: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface GreetingsCreate {
  id?: string;
  name: string;
  message?: string;
  locale?: string;
  metadata?: Record<string, unknown>;
  created_at?: string;
  updated_at?: string;
}

export interface GreetingsClient {
  list(query?: Query<Greetings>): Promise<Greetings[]>;
  get(id: string): Promise<Greetings | null>;
  create(data: GreetingsCreate): Promise<Greetings>;
  update(id: string, patch: Partial<GreetingsCreate>): Promise<Greetings>;
  delete(id: string): Promise<void>;
}

export interface Db {
  greetings: GreetingsClient;
}

export interface CreateDbConfig {
  adapter: 'mock' | 'remote' | 'runtime';
  seed?: Record<string, unknown[]>;
  endpoint?: string;
  token?: string;
  tenant?: string;
  context?: unknown;
}

export declare function createDb(config: CreateDbConfig): Db;
export declare const ENTITIES: Record<string, { table: string; pk: string; ops: string[]; columns: Record<string, unknown> }>;
